name: CI
#TESTS
# triggers pipeline when push is made to any branch (typical CI pipeline rule)
on: [push]

jobs:  
 dast_scan:
    name: Run DAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy PyGoat Application
        run: |
          docker build -f Dockerfile -t mytestapp:latest .
          docker run --rm -d -p 8000:8000 --name pygoat mytestapp:latest

      - name: Install Nikto
        run: |
          sudo apt-get update
          sudo apt-get install -y nikto

      - name: Run Nikto Scan
        run: |
          nikto -h http://localhost:8000 -o nikto-report.html

      - name: Upload Nikto Report
        uses: actions/upload-artifact@v3
        with:
          name: nikto-report.html
          path: nikto-report.html
